export default {
    "thérapie d’acceptation et d’engagement": "/therapie-acceptation-et-engagement/",
    ACT: "/therapie-acceptation-et-engagement/",
    "thérapie cognitive et comportementale": "/therapie-cognitive-et-comportementale/",
    TCC: "/therapie-cognitive-et-comportementale/",
    "TCC de 3e vague": "/tcc-troisieme-vague/",
    "pleine conscience": "/therapie-pleine-conscience/",
    psychothérapie: "/psychotherapie/",
    psychothérapies: "/psychotherapie/",
    hypnothérapie: "/blog/hypnotherapie/",
    EMDR: "/therapie-mosaic/",
    MOSAIC: "/therapie-mosaic/",
    "Doctolib": "https://www.doctolib.fr/psychologue/sceaux/nicolas-devaux-sceaux",

    // Ajouts conditionnels (symptômes / besoins)
    "anxiété": "/psychotherapie/",
    "dépression": "/psychotherapie/",
    "phobie": "/psychotherapie/",
    "attaques de panique": "/psychotherapie/",
    "attaque de panique": "/psychotherapie/",
    "burn-out": "/psychotherapie/",
    "ruminations": "/therapie-pleine-conscience/",
    "TOC": "/therapie-cognitive-et-comportementale/",
    "trouble obsessionnel-compulsif": "/therapie-cognitive-et-comportementale/",

    // Ajouts méthodes/approches complémentaires
    "méditation": "/therapie-pleine-conscience/",
    "thérapie centrée sur les émotions": "/blog/therapie-centree-emotions/",
    "thérapie de couple": "/therapie-couple/",
    "thérapie MOSAIC": "/therapie-mosaic/",
    "thérapie intégrative comportementale de couple": "/blog/therapie-integrative-comportementale-couple/",
    "IBCT": "/blog/therapie-integrative-comportementale-couple/",
    "thérapie fondée sur la compassion": "/therapie-fondee-compassion/",
    CFT: "/therapie-fondee-compassion/",

    // Parcours patient / informations pratiques
    "prendre rendez-vous": "/consulter/",
    consultation: "/consulter/",
    "psychologue en ligne": "/psychologue-en-ligne/",
    "consultation en ligne": "/psychologue-en-ligne/",
    "consultations en ligne": "/psychologue-en-ligne/",
    "téléconsultation": "/psychologue-en-ligne/",
    "visioconférence": "/psychologue-en-ligne/",
    "psychologue à Sceaux": "/psychologue-sceaux/",
    "groupes de pleine conscience": "/meditation-pleine-conscience-sceaux/",
    "groupe de pleine conscience": "/meditation-pleine-conscience-sceaux/",
    "gestion du stress": "/meditation-pleine-conscience-sceaux/",
    "psychologue à boulogne-billancourt": "/nicolas-devaux-psychologue/",
    "psychologue boulogne-billancourt": "/nicolas-devaux-psychologue/",

    // Villes voisines du cabinet (Sceaux)
    "psychologue antony": "/consulter/",
    "psychologue à antony": "/consulter/",
    "psychologue bourg-la-reine": "/consulter/",
    "psychologue à bourg-la-reine": "/consulter/",
    "psychologue châtenay-malabry": "/consulter/",
    "psychologue à châtenay-malabry": "/consulter/",
    "psychologue chatenay-malabry": "/consulter/",
    "psychologue fontenay-aux-roses": "/consulter/",
    "psychologue à fontenay-aux-roses": "/consulter/",
};
