export default {
    "thérapie d’acceptation et d’engagement": "/therapie-acceptation-et-engagement/",
    ACT: "/therapie-acceptation-et-engagement/",
    "thérapie cognitive et comportementale": "/therapie-cognitive-et-comportementale/",
    TCC: "/therapie-cognitive-et-comportementale/",
    "TCC de 3e vague": "/tcc-troisieme-vague/",
    "pleine conscience": "/therapie-pleine-conscience/",
    psychothérapie: "/psychotherapie/",
    psychothérapies: "/psychotherapie/",
    hypnothérapie: "/blog/hypnotherapie/",
    EMDR: "/therapie-mosaic/",
    MOSAIC: "/therapie-mosaic/",
    "Doctolib": "https://www.doctolib.fr/psychologue/sceaux/nicolas-devaux-sceaux",

    // Ajouts conditionnels (symptômes / besoins)
    "anxiété": "/psychotherapie/",
    "dépression": "/psychotherapie/",
    "phobie": "/psychotherapie/",
    "attaques de panique": "/psychotherapie/",
    "attaque de panique": "/psychotherapie/",
    "burn-out": "/psychotherapie/",
    "ruminations": "/blog/rumination-mentale/",
    "rumination": "/blog/rumination-mentale/",
    "rumination mentale": "/blog/rumination-mentale/",
    "TOC": "/therapie-cognitive-et-comportementale/",
    "trouble obsessionnel-compulsif": "/therapie-cognitive-et-comportementale/",
    "insomnie chronique": "/blog/insomnie-chronique/",
    "insomnie": "/blog/insomnie-chronique/",
    "sommeil réparateur": "/blog/sommeil-reparateur/",
    "TCC-I": "/blog/tcc-insomnie/",
    "TCCI": "/blog/tcc-insomnie/",
    "cohérence cardiaque": "/blog/coherence-cardiaque-365/",
    "cohérence cardiaque 365": "/blog/coherence-cardiaque-365/",

    // Ajouts méthodes/approches complémentaires
    "méditation": "/therapie-pleine-conscience/",
    "thérapie ACT": "/therapie-acceptation-et-engagement/",
    "thérapie centrée sur les émotions": "/blog/therapie-centree-emotions/",
    "thérapie de couple": "/therapie-couple/",
    "thérapie MOSAIC": "/therapie-mosaic/",
    "thérapie mosaic": "/therapie-mosaic/",
    "mosaic thérapie": "/therapie-mosaic/",
    "thérapie MOSAIC en ligne": "/therapie-mosaic/",
    "thérapie mosaic en ligne": "/therapie-mosaic/",
    "MOSAIC en ligne": "/therapie-mosaic/",
    "MOSAIC en visio": "/therapie-mosaic/",
    "séance MOSAIC": "/therapie-mosaic/",
    "thérapie intégrative comportementale de couple": "/blog/therapie-integrative-comportementale-couple/",
    "IBCT": "/blog/therapie-integrative-comportementale-couple/",
    "thérapie fondée sur la compassion": "/therapie-fondee-compassion/",
    CFT: "/therapie-fondee-compassion/",

    // Auto-évaluations (/outils/) — maillage vers les questionnaires en ligne
    "FSCRS": "/outils/fscrs/",
    "CompACT": "/outils/compact/",
    "AAQ-II": "/outils/aaq-ii/",
    "PCL-5": "/outils/pcl-5/",
    "stress post-traumatique": "/outils/pcl-5/",
    "PHQ-9": "/outils/phq-9-gad-7/",
    "GAD-7": "/outils/phq-9-gad-7/",
    "WHO-5": "/outils/who-5/",
    "schémas précoces inadaptés": "/outils/questionnaire-schemas-young/",
    "schémas de Young": "/outils/questionnaire-schemas-young/",

    // Parcours patient / informations pratiques
    "prendre rendez-vous": "/consulter/",
    consultation: "/consulter/",
    "psychologue en ligne": "/psychologue-en-ligne/",
    "consultation en ligne": "/psychologue-en-ligne/",
    "consultations en ligne": "/psychologue-en-ligne/",
    "téléconsultation": "/psychologue-en-ligne/",
    "visioconférence": "/psychologue-en-ligne/",
    "psychologue à Sceaux": "/psychologue-sceaux/",
    "psychologue Sceaux": "/psychologue-sceaux/",
    "groupes de pleine conscience": "/meditation-pleine-conscience-sceaux/",
    "groupe de pleine conscience": "/meditation-pleine-conscience-sceaux/",
    "gestion du stress": "/meditation-pleine-conscience-sceaux/",
    "psychologue à boulogne-billancourt": "/nicolas-devaux-psychologue/",
    "psychologue boulogne-billancourt": "/nicolas-devaux-psychologue/",

    // Villes voisines du cabinet (Sceaux) → page locale pilier
    "psychologue antony": "/psychologue-sceaux/",
    "psychologue à antony": "/psychologue-sceaux/",
    "psychologue bourg-la-reine": "/psychologue-sceaux/",
    "psychologue à bourg-la-reine": "/psychologue-sceaux/",
    "psychologue châtenay-malabry": "/psychologue-sceaux/",
    "psychologue à châtenay-malabry": "/psychologue-sceaux/",
    "psychologue chatenay-malabry": "/psychologue-sceaux/",
    "psychologue fontenay-aux-roses": "/psychologue-sceaux/",
    "psychologue à fontenay-aux-roses": "/psychologue-sceaux/",
};
